#ifndef __TEST_CONFIG_H
#define __TEST_CONFIG_H

#include "project_build_config.h"

/*
 * 专项测试档位。
 * PROJECT_TEST_TASKS_ENABLE由Common/project_build_config.h统一提供；
 * 正式固件保持0U，专项构建再临时覆盖为1U。
 */
#define PROJECT_TEST_PROFILE_SERVO_CAL             1U
#define PROJECT_TEST_PROFILE_K210_BALL_COMM        2U
#define PROJECT_TEST_PROFILE_BALL_MODEL_ID         3U
#define PROJECT_TEST_PROFILE_BALL_STATE_CONTROL    4U

#ifndef PROJECT_TEST_PROFILE
#define PROJECT_TEST_PROFILE \
    PROJECT_TEST_PROFILE_BALL_STATE_CONTROL
#endif

#if ((PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_SERVO_CAL) && \
     (PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_K210_BALL_COMM) && \
     (PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_BALL_MODEL_ID) && \
     (PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_BALL_STATE_CONTROL))
#error "PROJECT_TEST_PROFILE invalid"
#endif

#endif /* __TEST_CONFIG_H */
