#ifndef __TEST_CONFIG_H
#define __TEST_CONFIG_H

/*
 * 专项测试代码编译开关。
 *
 * PROJECT_TEST_TASKS_ENABLE=1U时使用下方测试档位；
 * 恢复为0U时重新使用H题第2项正式任务表。
 */
#ifndef PROJECT_TEST_TASKS_ENABLE
#define PROJECT_TEST_TASKS_ENABLE 1U
#endif

#define PROJECT_TEST_PROFILE_SERVO_CAL        1U
#define PROJECT_TEST_PROFILE_K210_BALL_COMM   2U
#define PROJECT_TEST_PROFILE_BALL_PID         3U

#ifndef PROJECT_TEST_PROFILE
#define PROJECT_TEST_PROFILE      PROJECT_TEST_PROFILE_K210_BALL_COMM 
#endif

#if ((PROJECT_TEST_TASKS_ENABLE != 0U) && \
     (PROJECT_TEST_TASKS_ENABLE != 1U))
#error "PROJECT_TEST_TASKS_ENABLE must be 0U or 1U"
#endif

#if ((PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_SERVO_CAL) && \
     (PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_K210_BALL_COMM) && \
     (PROJECT_TEST_PROFILE != PROJECT_TEST_PROFILE_BALL_PID))
#error "PROJECT_TEST_PROFILE invalid"
#endif

#endif /* __TEST_CONFIG_H */
